const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');

function inferConditions(parsedData = {}) {
  const conditions = [];
  const flags = { bp: null, glucose: null, bmi: null, ldl: null, hb: null };

  if (parsedData.blood_pressure) {
    const s = parsedData.blood_pressure.systolic;
    const d = parsedData.blood_pressure.diastolic;
    if (s >= 180 || d >= 120) {
      conditions.push('Hypertensive crisis'); flags.bp = 'red';
    } else if (s >= 140 || d >= 90) {
      conditions.push('Hypertension'); flags.bp = 'yellow';
    } else if (s >= 120 || d >= 80) {
      flags.bp = 'green';
    }
  }

  if (parsedData.glucose) {
    const g = parsedData.glucose.value;
    if (g >= 200) { conditions.push('Possible Diabetes (high glucose)'); flags.glucose = 'red'; }
    else if (g >= 126) { conditions.push('Possible Diabetes (fasting/glucose in diabetic range)'); flags.glucose = 'yellow'; }
    else flags.glucose = 'green';
  }

  if (parsedData.bmi) {
    const b = Number(parsedData.bmi);
    if (b >= 35) { conditions.push('Severe obesity'); flags.bmi = 'red'; }
    else if (b >= 30) { conditions.push('Obesity'); flags.bmi = 'yellow'; }
    else if (b >= 25) { flags.bmi = 'yellow'; }
    else flags.bmi = 'green';
  }

  if (parsedData.ldl) {
    const l = Number(parsedData.ldl);
    if (l >= 190) { conditions.push('Very high LDL (severe hypercholesterolemia)'); flags.ldl = 'red'; }
    else if (l >= 130) { conditions.push('High LDL (hyperlipidemia)'); flags.ldl = 'yellow'; }
    else flags.ldl = 'green';
  }

  if (parsedData.hemoglobin) {
    const hb = Number(parsedData.hemoglobin.value || parsedData.hemoglobin);
    if (!isNaN(hb)) {
      if (hb < 8) { conditions.push('Severe anemia'); flags.hb = 'red'; }
      else if (hb < 12) { conditions.push('Low hemoglobin (anemia)'); flags.hb = 'yellow'; }
      else flags.hb = 'green';
    }
  }

  return { conditions, flags };
}

function computeAlertLevel(flags) {
  // If any red -> red, else if >=2 yellow -> yellow, else green
  if (!flags) return 'green';
  const values = Object.values(flags);
  if (values.some(v => v === 'red')) return 'red';
  const yellowCount = values.filter(v => v === 'yellow').length;
  if (yellowCount >= 2) return 'yellow';
  return 'green';
}

async function createSummaryPDF({ memberName, reportTitle, reportDate, parsedData, inferred, alertLevel, summaryText }, outputPath) {
  return new Promise((resolve, reject) => {
    let PDFDocument;
    try {
      PDFDocument = require('pdfkit');
    } catch (err) {
      return reject(new Error("Missing dependency 'pdfkit'. Install with 'npm install pdfkit' in the backend folder."));
    }
    const doc = new PDFDocument({ autoFirstPage: false });
    const writeStream = fs.createWriteStream(outputPath);
    doc.pipe(writeStream);

    doc.addPage({ size: 'A4', margin: 50 });

    // Header with alert color
    const colorMap = { green: '#16a34a', yellow: '#f59e0b', red: '#dc2626' };
    const headerColor = colorMap[alertLevel] || '#16a34a';

    doc.rect(0, 0, doc.page.width, 60).fill(headerColor);
    doc.fillColor('#ffffff').fontSize(20).text('Health Report Summary', 50, 18);

    doc.moveDown();
    doc.fillColor('#000000');
    doc.fontSize(12).text(`Patient: ${memberName || 'Unknown'}`);
    doc.text(`Title: ${reportTitle}`);
    doc.text(`Date: ${new Date(reportDate).toLocaleString()}`);

    doc.moveDown();
    doc.fontSize(14).text('Key Findings', { underline: true });
    doc.moveDown(0.5);

    // Important vitals
    const keysToShow = ['blood_pressure', 'glucose', 'hemoglobin', 'ldl', 'bmi', 'weight'];
    keysToShow.forEach(k => {
      if (parsedData && parsedData[k]) {
        const v = parsedData[k];
        const label = k.replace('_', ' ').toUpperCase();
        doc.fontSize(11).text(`${label}: ${typeof v === 'object' ? JSON.stringify(v) : String(v)}`);
      }
    });

    doc.moveDown();
    doc.fontSize(14).text('Inferred Conditions', { underline: true });
    doc.moveDown(0.5);

    if (inferred.conditions.length === 0) doc.fontSize(11).text('No significant conditions detected.');
    else inferred.conditions.forEach(c => doc.fontSize(11).text(`- ${c}`));

    doc.moveDown();
    doc.fontSize(14).text('Summary', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text(summaryText || 'No summary available.');

    // Footer
    doc.moveDown(2);
    doc.fontSize(9).fillColor('#666').text('Generated by HealthVault', { align: 'center' });

    doc.end();

    writeStream.on('finish', () => resolve(outputPath));
    writeStream.on('error', reject);
  });
}

async function generateSummaryAndPDF({ report, member, summaryText }) {
  if (!report) throw new Error('report is required');

  const parsedData = report.parsedData || {};
  const inferred = inferConditions(parsedData);
  const alertLevel = computeAlertLevel(inferred.flags);

  // Construct a short summary text if not provided
  if (!summaryText) {
    if (inferred.conditions.length > 0) {
      summaryText = `The report indicates the following possible conditions: ${inferred.conditions.join('; ')}. Alert level: ${alertLevel.toUpperCase()}. Please consult a healthcare professional for confirmation.`;
    } else {
      summaryText = 'No major abnormalities detected in the key parameters parsed from the report.';
    }
  }

  // Build output path
  const fileName = `${uuidv4()}.pdf`;
  const uploadsDir = path.join(__dirname, '..', 'uploads');
  if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });
  const outPath = path.join(uploadsDir, fileName);

  await createSummaryPDF({
    memberName: member ? member.name : undefined,
    reportTitle: report.title || 'Report Summary',
    reportDate: report.date || new Date(),
    parsedData,
    inferred,
    alertLevel,
    summaryText
  }, outPath);

  return { outPath, fileName, summaryText, inferred, alertLevel };
}

module.exports = { inferConditions, computeAlertLevel, createSummaryPDF, generateSummaryAndPDF };
